### ISSUE TITLE
Cant set Cross-Origin Cookies

### ISSUE THREAD

**Issue by varunkumarmedam** [amag2511/webview_cookie_manager#16]
When I tried this plugin along with flutter_webview_plugin it can't able to read or write cookies from the Cross-Origin site. But this works fine in webview_flutter and flutter_inappwebview plugins.

**Comment by fryette** [comment]
As I know flutter_webview_plugin will be depricated soon or already. I would like to suggest to use webview_flutter.

**Comment by varunkumarmedam** [comment]
Yaa I used this plugin with webview_flutter but can't able to get cross-origin cookies. But I am able to get cross-origin cookies when I used flutter_inappwebview for my app.

**Comment by fryette** [comment]
Could you please share code how you are trying to get cross-origin cookies with flutter_inappwebview?

**Comment by varunkumarmedam** [comment]
I added no extra code for using flutter_inappwebview, the plugin itself manages cross-origin cookies. More generally, [Bloodline](https://play.google.com/store/apps/details?id=com.losersteam.bloodline) is my app which is built on flutter_inappwebview which manages cross-origin cookies which what I said earlier.

**Comment by fryette** [comment]
I really don't know how I can help here

**Comment by varunkumarmedam** [comment]
Have you ever tried to get cross-origin cookies using this plugin..?!

**Comment by amag2511** [comment]
@varunkumarmedam If you are talking about 'sameSite' value in the cookie, then you are right. For now, this value has not supported yet.

**Comment by varunkumarmedam** [comment]
Yaa thanks for the verification.

**Comment by your-diary** [comment]
Any updates?
I'm looking for a way to set `SameSite=Strict` cookie.
Because [`Cookie`](https://api.dart.dev/be/180791/dart-io/Cookie-class.html) class doesn't have `sameSite` field, is it still impossible?
Does anyone have any workaround?
