### ISSUE TITLE
Format exception

### ISSUE THREAD

**Issue by fryette** [amag2511/webview_cookie_manager#19]
if cookie.value = "{"123.123.123.123": 1234}:5678:9999"
webviewCookieManager.getCookies(url) is error.
FormatException: Invalid character in cookie value, code unit: '92' (at character 2)

**Comment by Vovanella95** [comment]
This issue is raised because " and spaces are not allowed in Cookie value. This exception raises in http_headers.dart file from dart:http lib. You just need to use valid cookie or add validation before assign it to Cookie(name, value).

I propose to close this issue.

@fryette
