### ISSUE TITLE
可否增加同步非webview的cookie

### ISSUE THREAD

**Issue by jasperchou** [amag2511/webview_cookie_manager#2]
准备引入flutter模块，正好在找cookie相关的，感谢分享。

看起来这个只可以用来同步webview的cookie，
能否也支持一下非webview的cookie管理？
也就是希望能支持native - webview - flutter 所有的cookie同步。

Ready to import the flutter module, just looking for cookie related. Thanks for sharing.

It looks like this is the only thing you can do to synchronize your WebView's cookies,
Can you also support non-WebView cookie management?
That is, I want to support all cookie synchronization of Native WebView Flutter.

**Comment by fryette** [comment]
Feel free to open a pull request!
In the future, we would like to support all methods in ios/Android CookieManager

**Comment by fryette** [comment]
Seems for now we support all features, new version will be published soon
