### ISSUE TITLE
document.cookie does not match the cookieManager.getCookies output

### ISSUE THREAD

**Issue by rodruiz** [amag2511/webview_cookie_manager#3]
Hi,
if you check **document.cookie** does not match the cookie provided.

```dart
onPageFinished: (_) async {
    final gotCookies = await cookieManager.getCookies(_url);
    for (var item in gotCookies) {
        print(item);
    }

    final String cookies = await _webViewController.evaluateJavascript('document.cookie');
    print('----- JS-COOKIES: $cookies -----');
},

```

Thanks.

**Comment by rodruiz** [comment]
ping @amag2511

**Comment by fryette** [comment]
@rodruiz which platform?

**Comment by rodruiz** [comment]
@fryette Android.

**Comment by fryette** [comment]
@rodruiz Seems your WebView plugin does not use the cookie manager to set cookies.
This plugin using native CookieManager to add cookies and don't have anything special in the flutter.

**Comment by rodruiz** [comment]
@fryette 
I'm using exactly the same plugin and code in your example file. I assume your plugin works properly with WebView.
You can add 


```dart
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: WebView(
          initialUrl: _url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) async {
            await cookieManager.setCookies([
              Cookie(cookieName, cookieValue)
                ..domain = domain
                ..expires = DateTime.now().add(Duration(days: 10))
            ]);
          },
          onPageFinished: (_) async {
            final gotCookies = await cookieManager.getCookies(_url);
            for (var item in gotCookies) {
              print(item);
            }

           ///// CHECK WEBVIEW IS USING COOKIE MANAGER
            final String cookies = await _webViewController.evaluateJavascript('document.cookie');
            print('----- JS-COOKIES: $cookies -----');
          },
        ),
      ),
    );
```

**Comment by fryette** [comment]
@rodruiz  Ok, You set cookie via `cookie manager` and cannot retrieve it by 'await _webViewController.evaluateJavascript('document.cookie');'?

**Comment by rodruiz** [comment]
@fryette I can retrieve all cookies available in the web document, but those cookies set by the cookie manager are not present. Seems like the webview is not using the cookie manager properly.

**Comment by fryette** [comment]
@rodruiz We had an issue on Android as well.
We cannot set cookies to Webview and decided to wrote this library.
Webview definitely using cookies from Android Cookie Manager but why we cannot retrieve it I don't know

**Comment by rodruiz** [comment]
@fryette If you can not get those cookies via JS means that the cookies are not included in the request to the website.

**Comment by rodruiz** [comment]
@fryette could you reopen this ticket and investigate further?
Another thing this plugin does not support using a domain like this (including a dot) when setting the cookie: **.mydomain.com**

**Comment by rodruiz** [comment]
Hi @fryette, just want to let you know that it's working now. 
Setting **httpOnly = false** did the trick.
Maybe you can add that to the README.
```dart
await cookieManager.setCookies([
  Cookie(cookieName, cookieValue)
    ..domain = domain
    ..expires = DateTime.now().add(Duration(days: 10)),
    ..httpOnly = false, // NOW document.cookie will work
]);
```

Thanks!!!

**Comment by fryette** [comment]
WOW!
Great!
I will update readme!
